"""Indian stock universes used by the trading agent."""

from __future__ import annotations

NIFTY_50 = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BEL.NS", "BHARTIARTL.NS",
    "BPCL.NS", "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "INDUSINDBK.NS",
    "INFY.NS", "ITC.NS", "JIOFIN.NS", "JSWSTEEL.NS", "KOTAKBANK.NS",
    "LTIM.NS", "LT.NS", "M&M.NS", "MARUTI.NS", "NESTLEIND.NS",
    "NTPC.NS", "ONGC.NS", "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS",
    "SBIN.NS", "SUNPHARMA.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
    "TCS.NS", "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS",
]

SENSEX_30 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "HINDUNILVR.NS", "ITC.NS", "LT.NS", "SBIN.NS", "AXISBANK.NS",
    "KOTAKBANK.NS", "BHARTIARTL.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "M&M.NS", "NTPC.NS", "TITAN.NS", "TATASTEEL.NS",
    "WIPRO.NS", "ULTRACEMCO.NS", "POWERGRID.NS", "NESTLEIND.NS", "HCLTECH.NS",
    "TECHM.NS", "BAJAJFINSV.NS", "INDUSINDBK.NS", "TATAMOTORS.NS", "JSWSTEEL.NS",
]

NIFTY_BANK = [
    "HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS", "SBIN.NS", "AXISBANK.NS",
    "INDUSINDBK.NS", "BANKBARODA.NS", "PNB.NS", "AUBANK.NS", "IDFCFIRSTB.NS",
    "FEDERALBNK.NS", "BANDHANBNK.NS",
]

NIFTY_NEXT_50 = [
    "ABB.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "AMBUJACEM.NS", "APOLLOTYRE.NS",
    "ASHOKLEY.NS", "AUROPHARMA.NS", "BANKBARODA.NS", "BHEL.NS", "CANBK.NS",
    "CHOLAFIN.NS", "DABUR.NS", "DIVISLAB.NS", "DLF.NS", "GAIL.NS",
    "GODREJCP.NS", "HAL.NS", "HAVELLS.NS", "IDBI.NS", "IDFCFIRSTB.NS",
    "INDIGO.NS", "INDUSTOWER.NS", "IRCTC.NS", "JINDALSTEL.NS", "LODHA.NS",
    "LUPIN.NS", "MOTHERSON.NS", "NAUKRI.NS", "NHPC.NS", "OIL.NS",
    "PAGEIND.NS", "PFC.NS", "PIDILITIND.NS", "PNB.NS", "POLYCAB.NS",
    "REC.NS", "SAIL.NS", "SIEMENS.NS", "SRF.NS", "TVSMOTOR.NS",
    "TORNTPHARM.NS", "TRENT.NS", "UNIONBANK.NS", "UPL.NS", "VBL.NS",
    "VEDL.NS", "ZYDUSLIFE.NS", "DMART.NS", "COLPAL.NS", "BERGEPAINT.NS",
]

NIFTY_100 = list(dict.fromkeys(NIFTY_50 + NIFTY_NEXT_50))

UNIVERSE_ASSETS = {
    "nifty_50": NIFTY_50,
    "sensex": SENSEX_30,
    "nifty_bank": NIFTY_BANK,
    "nifty_next_50": NIFTY_NEXT_50,
    "nifty_100": NIFTY_100,
    # Backward-compatible alias.
    "bse_50": SENSEX_30,
}

UNIVERSE_LABELS = {
    "nifty_50": "Nifty 50 (NSE Flagship)",
    "sensex": "S&P BSE Sensex (BSE Flagship)",
    "nifty_bank": "Nifty Bank (Banking Sector Benchmark)",
    "nifty_next_50": "Nifty Next 50 (Upcoming Bluechips)",
    "nifty_100": "Nifty 100 (Top 100 Combined)",
    "bse_50": "S&P BSE Sensex (BSE Flagship)",
}
